version: 0.2

phases:
  install:
    commands:
      - echo "Installing deps…"
      - npm ci
  build:
    commands:
      - echo "Building…"
      - npm run build || echo "No build script, continuing"
  post_build:
    commands:
      - echo "Build completed."

artifacts:
  files:
    - '**/*'
